version: "3.8"
services:
  backend:
    container_name: backend
    build:
      context: ./backend/bot_service
    volumes:
      - ./backend/bot_service/src:/app
    ports:
      - "8000:8000"
    stdin_open: true

  frontend:
    container_name: frontend
    build:
      context: ./frontend
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    depends_on:
      - backend
  mongo:
    image: mongo
    restart: always
    container_name: mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - ./backend/bot_service/db_data/:/data/db/
